name: Node.js Ingestion CI

on:
  push:
    branches: [ci-cd, main]
    paths:
      - "node-ingestion/**"
  pull_request:
    branches: [main]
    paths:
      - "node-ingestion/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Service containers to run with this job (Real Redis for testing)
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "./node-ingestion/package-lock.json"

      - name: Install Dependencies
        run: |
          cd node-ingestion
          npm ci

      - name: Code Linting
        run: |
          cd node-ingestion
          # Fails if code style doesn't match rules
          npm run lint

      - name: Security Audit
        run: |
          cd node-ingestion
          npm audit --audit-level=high

      - name: Run Tests
        env:
          REDIS_HOST: localhost
        run: |
          cd node-ingestion
          npm test

  # docker-push:
  #   needs: build-and-test # Only runs if tests pass
  #   if: github.ref == 'refs/heads/main' # Only push to Hub on main branch merge
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Build and Push
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: ./node-ingestion
  #         push: true
  #         tags: |
  #           ${{ secrets.DOCKERHUB_USERNAME }}/node-ingestion:latest
  #           ${{ secrets.DOCKERHUB_USERNAME }}/node-ingestion:${{ github.sha }}
  #         cache-from: type=gha
  #         cache-to: type=gha,mode=max
